{"url": ["https://www.baidu.com"]}
{"url": ["http://xueshu.baidu.com"]}
{"url": ["http://news.baidu.com"]}
{"url": ["https://passport.baidu.com/v2/?login&tpl=mn&u=http%3A%2F%2Fwww.baidu.com%2F&sms=5"]}
{"url": ["http://e.baidu.com/?refer=888"]}
{"url": ["http://v.baidu.com"]}
{"url": ["http://image.baidu.com"]}
{"url": ["http://home.baidu.com"]}
{"url": ["http://secr.baidu.com/"]}
{"url": ["http://jianyi.baidu.com/"]}
{"url": ["https://map.baidu.com/"]}
{"url": ["http://haokan.baidu.com"]}
{"url": ["https://tieba.baidu.com/index.html"]}
{"url": ["http://fanyi-pro.baidu.com/?from=bdmore"]}
{"url": ["http://ir.baidu.com/phoenix.zhtml?c=188488&p=irol-irhome"]}
{"url": ["http://bit.baidu.com/"]}
{"url": ["http://fanyi.baidu.com/"]}
{"url": ["https://wenku.baidu.com/"]}
{"url": ["https://xiongzhang.baidu.com/site/login"]}
{"url": ["http://zhaopin.baidu.com/"]}
{"url": ["http://site.baidu.com/"]}
{"url": ["http://quzheng.baidu.com/"]}
{"url": ["http://music.taihe.com/"]}
{"url": ["http://y.taihe.com/"]}
{"url": ["http://baijiahao.baidu.com/"]}
{"url": ["http://developer.baidu.com/vcast"]}
{"url": ["http://yingxiao.baidu.com/new/?castk=LTE%3D"]}
{"url": ["http://duer.baidu.com/"]}
{"url": ["http://video.baidu.com/"]}
{"url": ["https://zhuomian.baidu.com/"]}
{"url": ["http://vr.baidu.com"]}
{"url": ["http://waimai.baidu.com/waimai?qt=find"]}
{"url": ["https://trust.baidu.com/vstar/official/index/?fl=1&castk=LTE%3D"]}
{"url": ["https://koubei.baidu.com/"]}
{"url": ["http://cbbs.baidu.com"]}
{"url": ["http://test.baidu.com/crowdtest/crowdhome/guide"]}
{"url": ["https://pan.baidu.com"]}
{"url": ["http://youxi.baidu.com/"]}
{"url": ["https://jingyan.baidu.com/"]}
{"url": ["https://baike.baidu.com/"]}
{"url": ["http://app.baidu.com/"]}
{"url": ["https://jin.baidu.com/v/pds/loan/consumer/newlist/?processed_params=Array&channel=baidumore&sort=0"]}
{"url": ["https://anquan.baidu.com/pages/forum.html"]}
{"url": ["https://yuedu.baidu.com/"]}
{"url": ["http://motu.baidu.com/"]}
{"url": ["http://as.baidu.com/a/bdsuite"]}
{"url": ["http://weirenwu.baidu.com"]}
{"url": ["https://8.baidu.com/content/resource/app/index.html"]}
{"url": ["http://shoujiweishi.baidu.com/"]}
{"url": ["https://youke.baidu.com/"]}
{"url": ["http://mopai.baidu.com/home/"]}
{"url": ["http://m.browser.baidu.com/pc"]}
{"url": ["https://srfsh.baidu.com/default/"]}
{"url": ["https://jiaoyu.baidu.com/topic/bsplatform/overview"]}
{"url": ["http://lingxi.baidu.com/login/?fromu=http://lingxi.baidu.com&appid=336&u=http%3A%2F%2Flingxi.baidu.com%2F"]}
{"url": ["http://ai.baidu.com/index/"]}
{"url": ["https://h5.bce.baidu.com/"]}
{"url": ["http://lvshi.baidu.com/"]}
{"url": ["https://lvyou.baidu.com/"]}
{"url": ["https://baobao.baidu.com/"]}
{"url": ["http://qiao.baidu.com"]}
{"url": ["http://index.baidu.com/"]}
{"url": ["http://imageplus.baidu.com/"]}
{"url": ["http://top.baidu.com/"]}
{"url": ["http://ce.baidu.com/?from=more"]}
{"url": ["http://sinan.baidu.com/web/welcome/login"]}
{"url": ["https://open.baidu.com/"]}
{"url": ["http://apistore.baidu.com/"]}
{"url": ["https://su.baidu.com"]}
{"url": ["http://baitong.baidu.com/login.html"]}
{"url": ["https://mtj.baidu.com/web/welcome/login"]}
{"url": ["http://player.baidu.com/"]}
{"url": ["http://yuyin.baidu.com/"]}
{"url": ["http://yuqing.baidu.com/?castk=LTE%3D"]}
{"url": ["https://cloud.baidu.com/"]}
{"url": ["http://naotu.baidu.com"]}
{"url": ["http://mtc.baidu.com/"]}
{"url": ["https://liulanqi.baidu.com/"]}
{"url": ["http://tuijian.baidu.com/rec-web/welcome/login"]}
{"url": ["https://fuwu.baidu.com/index.html?_t=1533572224403"]}
{"url": ["https://hi.baidu.com"]}
{"url": ["http://wubi.baidu.com/"]}
{"url": ["http://sem.baidu.com/"]}
{"url": ["http://edu.baidu.com/"]}
{"url": ["http://help.baidu.com"]}
{"url": ["https://zhidao.baidu.com/"]}
{"url": ["https://ziyuan.baidu.com/?castk=LTE%3D"]}
{"url": ["https://shurufa.baidu.com/"]}
{"url": ["http://bim.baidu.com"]}
{"url": ["http://shouji.baidu.com"]}
{"url": ["http://j.baidu.com/mkt-web/welcome/login"]}
{"url": ["http://jian.news.baidu.com/"]}
{"url": ["http://newsalert.baidu.com/na?cmd=0"]}
{"url": ["http://push.baidu.com/"]}
{"url": ["https://gupiao.baidu.com/"]}
